# Generated by Django 5.2.4 on 2025-08-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='call_to_action',
            field=models.CharField(default='DÉCOUVRIR LA COLLECTION', max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='slogan',
            field=models.CharField(default='SAVOIR-FAIRE ITALIEN, ALLURE PARISIENNE', max_length=255),
        ),
    ]
