# Generated by Django 5.2.4 on 2025-08-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_brand_call_to_action_brand_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='call_to_action',
            field=models.CharField(blank=True, default='DÉCOUVRIR LA COLLECTION', max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, default='CHARLÈNE MORABITO', max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slogan',
            field=models.CharField(blank=True, default='SAVOIR-FAIRE ITALIEN, ALLURE PARISIENNE', max_length=255),
        ),
    ]
