# Generated by Django 5.2.4 on 2025-08-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_brand_call_to_action_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstHomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/first_section/')),
            ],
        ),
        migrations.CreateModel(
            name='SecondHomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/second_section/')),
            ],
        ),
    ]
