# Generated by Django 5.2.4 on 2025-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_firsthomesection_secondhomesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyToWearSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='home/ready_to_wear/')),
            ],
        ),
    ]
