# Generated by Django 5.2.4 on 2025-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_readytowearsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readytowearsection',
            name='background_image',
        ),
        migrations.AddField(
            model_name='readytowearsection',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='home/ready_section/'),
        ),
        migrations.AddField(
            model_name='readytowearsection',
            name='link_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='readytowearsection',
            name='link_url',
            field=models.URLField(blank=True),
        ),
    ]
