# Generated by Django 5.2.4 on 2025-08-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_readytowearsection_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookbookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LookbookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/lookbook/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.lookbooksection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
