# Generated by Django 5.2.4 on 2025-08-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_heritageblockone_heritageblockthree_heritageblocktwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
