# Generated by Django 5.2.4 on 2025-08-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_product_productdetail_productimage_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsize',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
