# Generated by Django 5.2.4 on 2025-08-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_productsize_is_out_of_stock_productsize_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReturnInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Livraison et Retours', max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
