# Generated by Django 5.2.4 on 2025-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_deliveryreturninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
