# Generated by Django 5.2.4 on 2025-08-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_featuredproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='slot',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Slot 1'), (2, 'Slot 2'), (3, 'Slot 3')], unique=True),
        ),
    ]
